#ifndef HALLMONITOR_DEFINITIONS_H
#define HALLMONITOR_DEFINITIONS_H

#include <vasq/logger.h>

#define HAMO_VERSION "0.1.0"

//#define HAMO_IPV6_SUPPORTED

#define IPV4_SIZE 4
#define IPV6_SIZE 16

enum hamoRetValue {
    HAMO_RET_OK = 0,
    HAMO_RET_USAGE,
    HAMO_RET_OTHER,
    HAMO_RET_BAD_WHITELIST,
    HAMO_RET_OUT_OF_MEMORY,
    HAMO_RET_OVERFLOW,
    HAMO_RET_PCAP_LOOKUP_DEVICE,
    HAMO_RET_PCAP_LOOKUP_NET,
    HAMO_RET_PCAP_OPEN,
    HAMO_RET_PCAP_DATALINK_UNSUPPORTED,
    HAMO_RET_PCAP_COMPILE,
    HAMO_RET_PCAP_SET_FILTER,
    HAMO_RET_PCAP_NO_FD,
    HAMO_RET_PCAP_SET_NONBLOCK,
    HAMO_RET_PCAP_DISPATCH,
    HAMO_RET_POLL_FAILED,
};

extern vasqLogger *hamo_logger;

#endif
